### PR TITLE
Support optional serde feature.

### PR DESCRIPTION
**Pull request by tmpfs**
Adds support for serde to the `Vcard` type using the `serde` feature flag.

### CODE REVIEW

**Comment by tmpfs** [comment]
@kenianbei, thanks so much for landing the chrono/time change so quickly.

For some context about this, I need to pass the Vcard type via some webassembly bindings to Javascript and serde is the only reasonable way for me to achieve this right now as I don't want to add another vCard parser to the Javascript side.

**Comment by kenianbei** [comment]
No problem, I have also done that before with wasm... I will take take a look at this tomorrow morning.

**Comment by kenianbei** [comment]
We should hold off on this until https://github.com/kenianbei/vcard_parser/issues/8 is resolved.

**Comment by tmpfs** [comment]
Hey @kenianbei,

I need this for my program and I also needed a parser that is fully compliant with RFC6350; your implementation deviates in some places, in particular I noticed the date/time handling is not compliant.

So I rolled my own here:

https://docs.rs/vcard4/latest/vcard4/

I reckon it's about 95% compliant with RFC6350, it is well tested with very good coverage. I wonder what you think? Maybe you want to try it out for your TUI? Would be cool if we could collaborate to get it to be fully compliant with the RFC.

Thanks 🙏

**Pull request closed without merging**
